"""
================================================================================
AEGIS Phase 2.2: tanh LUT Generator for VHDL
================================================================================
Generates a 256-entry tanh lookup table as a VHDL constant array.

Input range:  [-4.0, +4.0) mapped to 256 entries
Output range: [-1.0, +1.0] in Q8.8 format (signed 16-bit)

Also generates test vectors for GHDL testbench verification.
================================================================================
"""

import math
import sys
import os

# =========================================================================
# Configuration
# =========================================================================
LUT_SIZE = 256
INPUT_MIN = -4.0
INPUT_MAX = 4.0
INPUT_RANGE = INPUT_MAX - INPUT_MIN
STEP = INPUT_RANGE / LUT_SIZE  # 0.03125 per entry

FRAC_BITS = 8
SCALE = 1 << FRAC_BITS  # 256


def float_to_q88(value):
    """Convert float to Q8.8 signed 16-bit raw value."""
    raw = int(round(value * SCALE))
    raw = max(-32768, min(32767, raw))
    return raw


def q88_to_unsigned16(signed_val):
    """Convert signed Q8.8 to unsigned 16-bit (for VHDL std_logic_vector)."""
    if signed_val < 0:
        return signed_val + 65536
    return signed_val


def generate_lut():
    """Generate the 256-entry tanh LUT."""
    entries = []
    for i in range(LUT_SIZE):
        x = INPUT_MIN + i * STEP
        y = math.tanh(x)
        raw = float_to_q88(y)
        entries.append((i, x, y, raw))
    return entries


def write_vhdl_rom(entries, filepath):
    """Write VHDL package with ROM constant array."""
    with open(filepath, 'w') as f:
        f.write("--------------------------------------------------------------------------------\n")
        f.write("-- AEGIS Phase 2.2: tanh Lookup Table ROM (Auto-Generated)\n")
        f.write("--------------------------------------------------------------------------------\n")
        f.write("-- DO NOT EDIT MANUALLY — Generated by generate_tanh_lut.py\n")
        f.write(f"-- {LUT_SIZE} entries, input range [{INPUT_MIN}, {INPUT_MAX})\n")
        f.write(f"-- Step size: {STEP:.6f}\n")
        f.write(f"-- Output format: Q8.8 signed (16-bit)\n")
        f.write("--------------------------------------------------------------------------------\n\n")
        f.write("library ieee;\n")
        f.write("use ieee.std_logic_1164.all;\n\n")
        f.write("package tanh_lut_pkg is\n\n")
        f.write(f"    constant TANH_LUT_SIZE : integer := {LUT_SIZE};\n")
        f.write(f"    constant TANH_ADDR_BITS : integer := 8;  -- log2({LUT_SIZE})\n\n")
        f.write("    type tanh_rom_t is array (0 to TANH_LUT_SIZE - 1) of\n")
        f.write("        std_logic_vector(15 downto 0);\n\n")
        f.write("    constant TANH_ROM : tanh_rom_t := (\n")

        for i, (idx, x, y, raw) in enumerate(entries):
            unsigned = q88_to_unsigned16(raw)
            comma = "," if i < LUT_SIZE - 1 else " "
            y_str = f"{y:+.6f}"
            f.write(f'        x"{unsigned:04X}"{comma}  '
                    f'-- [{idx:3d}] x={x:+.4f}  tanh={y_str}\n')

        f.write("    );\n\n")
        f.write("end package tanh_lut_pkg;\n")

    print(f"[VHDL] Generated: {filepath}")


def write_test_vectors(entries, filepath):
    """Write CSV test vectors for GHDL testbench."""
    # Generate comprehensive test points
    test_points = []

    # 1. Saturation boundaries
    test_points.append((-5.0, "below_min"))
    test_points.append((-4.0, "at_min"))
    test_points.append((4.0, "at_max"))
    test_points.append((5.0, "above_max"))

    # 2. Key mathematical values
    test_points.append((0.0, "zero"))
    test_points.append((1.0, "one"))
    test_points.append((-1.0, "neg_one"))
    test_points.append((0.5, "half"))
    test_points.append((-0.5, "neg_half"))
    test_points.append((2.0, "two"))
    test_points.append((-2.0, "neg_two"))
    test_points.append((3.0, "three"))
    test_points.append((-3.0, "neg_three"))

    # 3. LUT boundary values
    test_points.append((-3.96875, "first_entry"))
    test_points.append((3.96875, "last_entry"))

    # 4. Some intermediate values
    for x in [0.25, -0.25, 0.75, -0.75, 1.5, -1.5]:
        test_points.append((x, f"val_{x}"))

    with open(filepath, 'w') as f:
        f.write("x_hex,expected_hex,description\n")

        for x_float, desc in test_points:
            x_raw = float_to_q88(x_float)
            x_unsigned = q88_to_unsigned16(x_raw)

            # Compute expected output
            if x_float <= INPUT_MIN:
                y_raw = float_to_q88(-1.0)
            elif x_float >= INPUT_MAX:
                y_raw = float_to_q88(1.0)
            else:
                # Direct LUT lookup (no interpolation in VHDL)
                idx = int((x_float - INPUT_MIN) / STEP)
                idx = max(0, min(LUT_SIZE - 1, idx))
                y_raw = entries[idx][3]  # raw Q8.8

            y_unsigned = q88_to_unsigned16(y_raw)
            f.write(f"{x_unsigned:04X},{y_unsigned:04X},{desc}\n")

    print(f"[TEST] Generated: {filepath} ({len(test_points)} vectors)")
    return test_points


def validate_accuracy(entries):
    """Measure maximum error vs float tanh."""
    max_err = 0.0
    max_err_x = 0.0

    for idx, x, y_true, raw in entries:
        y_q88 = raw / SCALE
        err = abs(y_true - y_q88)
        if err > max_err:
            max_err = err
            max_err_x = x

    print(f"\n[ACCURACY]")
    print(f"  LUT entries:    {LUT_SIZE}")
    print(f"  Q8.8 resolution: {1.0/SCALE:.6f}")
    print(f"  Max error:      {max_err:.6f} (at x={max_err_x:.4f})")
    print(f"  Criterion:      < 0.020")
    print(f"  Status:         {'PASS' if max_err < 0.02 else 'FAIL'}")

    return max_err < 0.02


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else os.getcwd()

    entries = generate_lut()

    # Write VHDL ROM package
    vhdl_path = os.path.join(script_dir, '..', '..', 'rtl', 'aegis', 'tanh_lut_pkg.vhd')
    vhdl_path = os.path.normpath(vhdl_path)
    write_vhdl_rom(entries, vhdl_path)

    # Write test vectors
    test_path = os.path.join(script_dir, '..', '..', 'rtl', 'aegis', 'test_vectors_tanh.csv')
    test_path = os.path.normpath(test_path)
    write_test_vectors(entries, test_path)

    # Validate accuracy
    passed = validate_accuracy(entries)

    if not passed:
        sys.exit(1)

    print("\n[DONE] All Phase 2.2 generator outputs created.")


if __name__ == '__main__':
    main()
