"""
AEGIS Phase 2.3: ESN Weight Generator + Golden Reference
Generates VHDL weight package (CSR sparse format) and test vectors.
"""
import numpy as np
import math
import os, sys

# ========== Configuration ==========
ESN_N = 8            # Neurons (small for verification)
SPARSITY = 0.75      # W sparsity (75% zeros -> ~2 nonzero/row for N=8)
SPECTRAL_RADIUS = 0.9
INPUT_SCALING = 0.5
LEAK_RATE = 0.3      # alpha in leaky integrator
SEED = 42
FRAC = 8
SCALE = 1 << FRAC    # 256

# tanh LUT (must match VHDL exactly)
TANH_LUT_SIZE = 256
TANH_INPUT_MIN = -4.0
TANH_STEP = 8.0 / TANH_LUT_SIZE

def float_to_q88(v):
    raw = int(round(v * SCALE))
    return max(-32768, min(32767, raw))

def q88_to_float(raw):
    if raw >= 32768: raw -= 65536
    return raw / SCALE

def to_u16(signed_val):
    return signed_val & 0xFFFF

# Build tanh LUT (same as VHDL)
TANH_LUT = []
for i in range(TANH_LUT_SIZE):
    x = TANH_INPUT_MIN + i * TANH_STEP
    TANH_LUT.append(float_to_q88(math.tanh(x)))

def tanh_q88(x_raw):
    """Exact VHDL tanh lookup."""
    if x_raw <= -1024: return float_to_q88(-1.0)
    if x_raw >= 1024:  return float_to_q88(1.0)
    addr = (x_raw + 1024) >> 3
    addr = max(0, min(255, addr))
    return TANH_LUT[addr]

def q88_mul(a, b):
    """Q8.8 multiply matching VHDL: (a*b) >> 8, saturate to 16-bit."""
    product = a * b  # 32-bit
    shifted = product >> FRAC if product >= 0 else -((-product) >> FRAC)
    return max(-32768, min(32767, shifted))

def generate_weights():
    """Generate ESN weights, return (W_in, W_csr, W_dense)."""
    rng = np.random.default_rng(SEED)
    
    # Input weights
    W_in = rng.uniform(-INPUT_SCALING, INPUT_SCALING, ESN_N)
    
    # Reservoir weights (sparse)
    W = rng.uniform(-1, 1, (ESN_N, ESN_N))
    mask = rng.random((ESN_N, ESN_N)) > SPARSITY
    W = W * mask
    
    # Scale to spectral radius
    eigenvalues = np.linalg.eigvals(W)
    max_eig = np.max(np.abs(eigenvalues))
    if max_eig > 0:
        W = W * (SPECTRAL_RADIUS / max_eig)
    
    # Quantize to Q8.8
    W_in_q = [float_to_q88(w) for w in W_in]
    W_q = [[float_to_q88(W[i, j]) for j in range(ESN_N)] for i in range(ESN_N)]
    
    # CSR format
    row_ptr = [0]
    col_idx = []
    values = []
    for i in range(ESN_N):
        for j in range(ESN_N):
            if W_q[i][j] != 0:
                col_idx.append(j)
                values.append(W_q[i][j])
        row_ptr.append(len(col_idx))
    
    nnz = len(values)
    return W_in_q, row_ptr, col_idx, values, nnz


def golden_reference(W_in_q, row_ptr, col_idx, values, inputs):
    """Run ESN with exact VHDL arithmetic, return state history."""
    leak_q = float_to_q88(LEAK_RATE)
    state = [0] * ESN_N
    history = []
    
    for inp_float in inputs:
        inp_q = float_to_q88(inp_float)
        new_state = [0] * ESN_N
        
        for i in range(ESN_N):
            # MAC: acc = W_in[i]*input + sum(W[i][j]*state[j])
            acc = W_in_q[i] * inp_q  # 32-bit product (Q16.16)
            for ptr in range(row_ptr[i], row_ptr[i + 1]):
                j = col_idx[ptr]
                acc += values[ptr] * state[j]
            
            # Shift to Q8.8 with saturation
            if acc >= 0:
                tanh_in = acc >> FRAC
            else:
                tanh_in = -((-acc) >> FRAC)
            tanh_in = max(-32768, min(32767, tanh_in))
            
            # tanh lookup
            tanh_out = tanh_q88(tanh_in)
            
            # Leak: new = old + leak*(tanh - old)
            diff = tanh_out - state[i]
            diff = max(-32768, min(32767, diff))
            leak_term = q88_mul(leak_q, diff)
            ns = state[i] + leak_term
            new_state[i] = max(-32768, min(32767, ns))
        
        state = new_state[:]
        history.append([to_u16(s) for s in state])
    
    return history


def write_vhdl_pkg(W_in_q, row_ptr, col_idx, values, nnz, filepath):
    """Write VHDL weight package."""
    leak_q = float_to_q88(LEAK_RATE)
    with open(filepath, 'w') as f:
        f.write("-- AEGIS Phase 2.3: ESN Weight Package (Auto-Generated)\n")
        f.write("-- DO NOT EDIT — generated by generate_esn_weights.py\n\n")
        f.write("library ieee;\nuse ieee.std_logic_1164.all;\n\n")
        f.write("package esn_weight_pkg is\n\n")
        f.write(f"    constant ESN_N   : integer := {ESN_N};\n")
        f.write(f"    constant ESN_NNZ : integer := {nnz};\n\n")
        f.write("    type slv16_array is array (natural range <>) of\n")
        f.write("        std_logic_vector(15 downto 0);\n")
        f.write("    type int_array is array (natural range <>) of integer;\n\n")
        
        # Leak rate
        f.write(f"    constant ESN_LEAK : std_logic_vector(15 downto 0) "
                f":= x\"{to_u16(leak_q):04X}\";  -- {LEAK_RATE}\n\n")
        
        # W_in
        f.write(f"    constant ESN_W_IN : slv16_array(0 to {ESN_N-1}) := (\n")
        for i, w in enumerate(W_in_q):
            comma = "," if i < ESN_N - 1 else " "
            f.write(f'        x"{to_u16(w):04X}"{comma}  -- [{i}] {q88_to_float(w):+.4f}\n')
        f.write("    );\n\n")
        
        # Row pointers
        f.write(f"    constant ESN_W_ROW_PTR : int_array(0 to {ESN_N}) := (\n")
        for i, p in enumerate(row_ptr):
            comma = "," if i < ESN_N else " "
            f.write(f"        {p}{comma}\n")
        f.write("    );\n\n")
        
        if nnz > 0:
            # Column indices
            f.write(f"    constant ESN_W_COL_IDX : int_array(0 to {nnz-1}) := (\n")
            for i, c in enumerate(col_idx):
                comma = "," if i < nnz - 1 else " "
                f.write(f"        {c}{comma}\n")
            f.write("    );\n\n")
            
            # Values
            f.write(f"    constant ESN_W_VALUES : slv16_array(0 to {nnz-1}) := (\n")
            for i, v in enumerate(values):
                comma = "," if i < nnz - 1 else " "
                f.write(f'        x"{to_u16(v):04X}"{comma}  -- {q88_to_float(v):+.4f}\n')
            f.write("    );\n\n")
        
        f.write("end package esn_weight_pkg;\n")
    print(f"[VHDL] {filepath}  (N={ESN_N}, NNZ={nnz})")


def write_test_vectors(history, inputs, filepath):
    """Write golden reference CSV."""
    with open(filepath, 'w') as f:
        # Header
        cols = ",".join([f"s{i}" for i in range(ESN_N)])
        f.write(f"step,input_hex,{cols}\n")
        for step, (inp, states) in enumerate(zip(inputs, history)):
            inp_hex = f"{to_u16(float_to_q88(inp)):04X}"
            s_hex = ",".join([f"{s:04X}" for s in states])
            f.write(f"{step},{inp_hex},{s_hex}\n")
    print(f"[TEST] {filepath}  ({len(history)} steps)")


def main():
    base = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                          '..', '..', 'rtl', 'aegis'))
    
    W_in_q, row_ptr, col_idx, values, nnz = generate_weights()
    
    # Test inputs: 5 steps with known values
    inputs = [0.5, -0.3, 0.8, -0.1, 0.6]
    history = golden_reference(W_in_q, row_ptr, col_idx, values, inputs)
    
    write_vhdl_pkg(W_in_q, row_ptr, col_idx, values, nnz,
                   os.path.join(base, 'esn_weight_pkg.vhd'))
    write_test_vectors(history, inputs, os.path.join(base, 'test_vectors_esn.csv'))
    
    # Print summary
    print(f"\n[SUMMARY]")
    print(f"  Neurons: {ESN_N}")
    print(f"  Nonzero W: {nnz} / {ESN_N*ESN_N} ({100*nnz/(ESN_N*ESN_N):.0f}%)")
    print(f"  Leak rate: {LEAK_RATE} (Q8.8 = 0x{to_u16(float_to_q88(LEAK_RATE)):04X})")
    nnz_per_row = [row_ptr[i+1]-row_ptr[i] for i in range(ESN_N)]
    cycles = sum(3 + k for k in nnz_per_row) + 1
    print(f"  NNZ/row: {nnz_per_row}")
    print(f"  Est. cycles: {cycles} (target <100)")
    
    # Show first step states
    print(f"\n  Step 0 states (input={inputs[0]}):")
    for j in range(ESN_N):
        raw = history[0][j]
        signed_val = raw - 65536 if raw >= 32768 else raw
        print(f"    s[{j}] = 0x{raw:04X} = {signed_val/256:+.4f}")


if __name__ == '__main__':
    main()
