-- AEGIS Phase 2.3: ESN Weight Package (Auto-Generated)
-- DO NOT EDIT — generated by generate_esn_weights.py

library ieee;
use ieee.std_logic_1164.all;

package esn_weight_pkg is

    constant ESN_N   : integer := 8;
    constant ESN_NNZ : integer := 11;

    type slv16_array is array (natural range <>) of
        std_logic_vector(15 downto 0);
    type int_array is array (natural range <>) of integer;

    constant ESN_LEAK : std_logic_vector(15 downto 0) := x"004D";  -- 0.3

    constant ESN_W_IN : slv16_array(0 to 7) := (
        x"0046",  -- [0] +0.2734
        x"FFF0",  -- [1] -0.0625
        x"005C",  -- [2] +0.3594
        x"0033",  -- [3] +0.1992
        x"FF98",  -- [4] -0.4062
        x"007A",  -- [5] +0.4766
        x"0043",  -- [6] +0.2617
        x"0049"   -- [7] +0.2852
    );

    constant ESN_W_ROW_PTR : int_array(0 to 8) := (
        0,
        2,
        3,
        3,
        6,
        8,
        10,
        10,
        11 
    );

    constant ESN_W_COL_IDX : int_array(0 to 10) := (
        0,
        7,
        2,
        3,
        4,
        7,
        0,
        5,
        3,
        4,
        3 
    );

    constant ESN_W_VALUES : slv16_array(0 to 10) := (
        x"FF41",  -- -0.7461
        x"FF74",  -- -0.5469
        x"00A8",  -- +0.6562
        x"FF60",  -- -0.6250
        x"FF42",  -- -0.7422
        x"0057",  -- +0.3398
        x"FFE0",  -- -0.1250
        x"009D",  -- +0.6133
        x"FF03",  -- -0.9883
        x"0094",  -- +0.5781
        x"FF9B"   -- -0.3945
    );

end package esn_weight_pkg;
